"Resource/UI/Quests/QuestObjectivePanel_InGame_Base.res"
{
	"QuestObjectiveTextPanel"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"QuestObjectiveTextPanel"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"3"
		"wide"										"250"
		"tall"										"18"
		"visible"									"1"
		"enabled"									"1"

		"PaintBackgroundType"						"2"

		"enabled_text_color_override"				"White"
		"disabled_text_color_override"				"Gray"

		"normal_token"								"#QuestObjective_Required"
		"advanced_token"							"#QuestObjective_Optional"
	}
	"AttribGlow"
	{
		"ControlName"								"Label"
		"fieldName"									"AttribGlow"
		"xpos"										"rs1"
		"ypos"										"0"
		"wide"										"f0"
		"tall"										"18"
		"zpos"										"5"
		"labeltext"									"%attr_desc%"
		"font"										"QuestObjectiveTracker_DescGlow"
		"TextAlignment"								"north-east"
		"textinsetx"								"5"
		"alpha"										"0"
		"proportionaltoparent"						"1"
	}
	"AttribDesc"
	{
		"ControlName"								"Label"
		"fieldName"									"AttribDesc"
		"xpos"										"rs1"
		"ypos"										"0"
		"wide"										"f0"
		"tall"										"18"
		"zpos"										"4"
		"labeltext"									"%attr_desc%"
		"font"										"QuestObjectiveTracker_Desc"
		"TextAlignment"								"north-east"
		"textinsetx"								"5"
		"proportionaltoparent"						"1"
	}
	"AttribBlur"
	{
		"ControlName"								"Label"
		"fieldName"									"AttribBlur"
		"xpos"										"rs1"
		"ypos"										"0"
		"wide"										"f0"
		"tall"										"10"
		"zpos"										"3"
		"visible"									"1"
		"font"										"QuestObjectiveTracker_DescBlur"
		"labeltext"									"%attr_desc%"
		"textAlignment"								"north-east"
		"textinsetx"								"5"
		"proportionaltoparent"						"1"
		"fgcolor_override"							"White"
	}
}