// Remember, manual positioning or the scrollbar get's angry!
// Using + positioning to keep the gaps accurate

"Resource/UI/Customizations/#Customization_Menu/HUD_Customization_Colors.res"
{
	"SafeMode"
	{
		"Customizations_Scroller"
		{
			"HUD_Theme_Selection"
			{
				"ControlName"							"EditablePanel"
				"fieldName"								"HUD_Theme_Selection"
				"xpos"									"2"
				"ypos"									"53"
				"zpos"									"0"
				"wide"									"f8"
				"tall"									"100"
				"visible"								"1"
				"enabled"								"1"
				"proportionaltoparent"					"1"
				"paintBackground"						"1"
				"paintBackgroundType"					"2"
				"roundedcorners"						"3"
				"bgcolor_override"						"FooterBGBlack"

				"Title"
				{
					"ControlName"						"CExLabel"
					"fieldName"							"Title"
					"xpos"								"0"
					"ypos"								"0"
					"zpos"								"0"
					"wide"								"f0"
					"tall"								"14"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"use_proportional_insets"			"1"
					"labelText"							"HUD Themes (Themes aren't limited to the health, it will be applied everywhere!)"
					"font"								"ItemFontNameSmallest"
					"textAlignment"						"west"
					"textinsetx"						"5"
					"fgcolor"							"White"
					"paintbackground"					"1"
					"paintBackgroundType"				"2"
					"roundedcorners"					"3"
					"bgcolor_override"					"StoreGreen"
				}
				"Warning"
				{
					"ControlName"						"CExLabel"
					"fieldName"							"Warning"
					"xpos"								"-1"
					"ypos"								"-1"
					"zpos"								"1"
					"wide"								"170"
					"tall"								"12"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"labelText"							"Theme Changes Require a Game Restart!"
					"font"								"FontStoreOriginalPrice"
					"textAlignment"						"center"
					"fgcolor"							"White"
					"paintbackground"					"1"
					"paintBackgroundType"				"2"
					"bgcolor_override"					"Red"

					"pin_to_sibling"					"Title"
					"pin_corner_to_sibling"				"PIN_TOPRIGHT"
					"pin_to_sibling_corner"				"PIN_TOPRIGHT"
				}
				"Themes_Scroller"
				{
					"ControlName"						"CScrollableList"
					"fieldName"							"Themes_Scroller"
					"xpos"								"cs-0.5"
					"ypos"								"rs1-1"
					"zpos"								"20"
					"wide"								"f2"
					"tall"								"f17"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"

					"Scrollbar"
					{
						"xpos"							"rs1+1"
						"ypos"							"0"
						"wide"							"4"
						"tall"							"f0"
						"zpos"							"1000"
						"proportionaltoparent"			"1"

						"Slider"
						{
							"PaintBackgroundType"		"0"
							"fgcolor_override"			"White"
						}

						"nobuttons"						"1"
					}
//=================================================================================================================================
// DEFAULT THEME
//=================================================================================================================================
					"Theme_Reset"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Theme_Reset"
						"xpos"							"1"
						"ypos"							"0"
						"zpos"							"20"
						"wide"							"56"
						"tall"							"40"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"Red"

						"Theme_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Name"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"wrap"						"1"
							"centerwrap"				"1"
							"font"						"ItemFontNameSmallest"
							"labeltext"					"Reset to Default"
							"textAlignment"				"center"
							"fgcolor"					"Black"
						}
						"Theme_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_default"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
//=================================================================================================================================
// WHITE THEME
//=================================================================================================================================
					"Theme_White"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Theme_White"
						"xpos"							"59"
						"ypos"							"0"
						"zpos"							"20"
						"wide"							"57"
						"tall"							"40"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"Health_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Health_Image"
							"xpos"						"cs-0.5"
							"ypos"						"rs1+4"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/health_white"
						}
						"Theme_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Name"
							"xpos"						"cs-0.5"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"White"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"White"
						}
						"Theme_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_white"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
//=================================================================================================================================
// GREEN THEME
//=================================================================================================================================
					"Theme_Green"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Theme_Green"
						"xpos"							"1+117"
						"ypos"							"0"
						"zpos"							"20"
						"wide"							"115"
						"tall"							"40"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"Health_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Health_Image"
							"xpos"						"9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/shadow_green"
						}
						"Shadow_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Shadow_Image"
							"xpos"						"rs1-9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/health_green"
						}
						"Separator"
						{
							"ControlName"				"Panel"
							"fieldName"					"Separator"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"2"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Theme_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Name"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Green"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reGreen"
						}
						"Theme_Shadow"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Shadow"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reGreen"
						}
						"Theme_Numbers"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.50"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Numbers"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reGreen"
						}
						"Theme_Button_Shadow"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_green"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
						"Theme_Button_Numbers"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.50"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_alt_green"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
//=================================================================================================================================
// BLUE THEME
//=================================================================================================================================
					"Theme_Blue"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Theme_Blue"
						"xpos"							"1+117+117"
						"ypos"							"0"
						"zpos"							"20"
						"wide"							"115"
						"tall"							"40"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"Health_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Health_Image"
							"xpos"						"9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/shadow_blue"
						}
						"Shadow_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Shadow_Image"
							"xpos"						"rs1-9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/health_blue"
						}
						"Separator"
						{
							"ControlName"				"Panel"
							"fieldName"					"Separator"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"2"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Theme_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Name"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Blue"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reBlue"
						}
						"Theme_Shadow"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Shadow"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reBlue"
						}
						"Theme_Numbers"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Numbers"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reBlue"
						}
						"Theme_Button_Shadow"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_blue"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
						"Theme_Button_Numbers"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_alt_blue"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
//=================================================================================================================================
// CYAN THEME
//=================================================================================================================================
					"Theme_Cyan"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Theme_Cyan"
						"xpos"							"1+117+117+117"
						"ypos"							"0"
						"zpos"							"20"
						"wide"							"115"
						"tall"							"40"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"Health_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Health_Image"
							"xpos"						"9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/shadow_cyan"
						}
						"Shadow_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Shadow_Image"
							"xpos"						"rs1-9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/health_cyan"
						}
						"Separator"
						{
							"ControlName"				"Panel"
							"fieldName"					"Separator"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"2"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Theme_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Name"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Cyan"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reCyan"
						}
						"Theme_Shadow"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Shadow"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reCyan"
						}
						"Theme_Numbers"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Numbers"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reCyan"
						}
						"Theme_Button_Shadow"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_cyan"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
						"Theme_Button_Numbers"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_alt_cyan"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
//=================================================================================================================================
// PURPLE THEME
//=================================================================================================================================
					"Theme_Purple"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Theme_Purple"
						"xpos"							"1+117+117+117+117"
						"ypos"							"0"
						"zpos"							"20"
						"wide"							"115"
						"tall"							"40"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"Health_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Health_Image"
							"xpos"						"9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/shadow_purple"
						}
						"Shadow_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Shadow_Image"
							"xpos"						"rs1-9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/health_purple"
						}
						"Separator"
						{
							"ControlName"				"Panel"
							"fieldName"					"Separator"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"2"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Theme_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Name"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Purple"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0rePurple"
						}
						"Theme_Shadow"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Shadow"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0rePurple"
						}
						"Theme_Numbers"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Numbers"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0rePurple"
						}
						"Theme_Button_Shadow"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_purple"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
						"Theme_Button_Numbers"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_alt_purple"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
//=================================================================================================================================
// GREY THEME
//=================================================================================================================================
					"Theme_Grey"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Theme_Grey"
						"xpos"							"1"
						"ypos"							"0+42"
						"zpos"							"20"
						"wide"							"115"
						"tall"							"40"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"Health_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Health_Image"
							"xpos"						"9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/shadow_grey"
						}
						"Shadow_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Shadow_Image"
							"xpos"						"rs1-9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/health_grey"
						}
						"Separator"
						{
							"ControlName"				"Panel"
							"fieldName"					"Separator"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"2"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Theme_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Name"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Grey"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reGrey"
						}
						"Theme_Shadow"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Shadow"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reGrey"
						}
						"Theme_Numbers"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Numbers"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reGrey"
						}
						"Theme_Button_Shadow"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_grey"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
						"Theme_Button_Numbers"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_alt_grey"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
//=================================================================================================================================
// RED DARK THEME
//=================================================================================================================================
					"Theme_Red_Dark"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Theme_Red_Dark"
						"xpos"							"1+117"
						"ypos"							"0+42"
						"zpos"							"20"
						"wide"							"115"
						"tall"							"40"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"Health_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Health_Image"
							"xpos"						"9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/shadow_red_dark"
						}
						"Shadow_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Shadow_Image"
							"xpos"						"rs1-9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/health_red_dark"
						}
						"Separator"
						{
							"ControlName"				"Panel"
							"fieldName"					"Separator"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"2"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Theme_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Name"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Red Dark"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reRedDark"
						}
						"Theme_Shadow"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Shadow"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reRedDark"
						}
						"Theme_Numbers"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Numbers"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reRedDark"
						}
						"Theme_Button_Shadow"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_reddark"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
						"Theme_Button_Numbers"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_alt_reddark"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
//=================================================================================================================================
// RED THEME
//=================================================================================================================================
					"Theme_Red"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Theme_Red"
						"xpos"							"1+117+117"
						"ypos"							"0+42"
						"zpos"							"20"
						"wide"							"115"
						"tall"							"40"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"Health_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Health_Image"
							"xpos"						"9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/shadow_red"
						}
						"Shadow_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Shadow_Image"
							"xpos"						"rs1-9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/health_red"
						}
						"Separator"
						{
							"ControlName"				"Panel"
							"fieldName"					"Separator"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"2"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Theme_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Name"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Red"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reRed"
						}
						"Theme_Shadow"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Shadow"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reRed"
						}
						"Theme_Numbers"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Numbers"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reRed"
						}
						"Theme_Button_Shadow"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_red"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
						"Theme_Button_Numbers"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_alt_red"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
//=================================================================================================================================
// ORANGE THEME
//=================================================================================================================================
					"Theme_Orange"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Theme_Orange"
						"xpos"							"1+117+117+117"
						"ypos"							"0+42"
						"zpos"							"20"
						"wide"							"115"
						"tall"							"40"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"Health_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Health_Image"
							"xpos"						"9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/shadow_orange"
						}
						"Shadow_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Shadow_Image"
							"xpos"						"rs1-9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/health_orange"
						}
						"Separator"
						{
							"ControlName"				"Panel"
							"fieldName"					"Separator"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"2"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Theme_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Name"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Orange"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reOrange"
						}
						"Theme_Shadow"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Shadow"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reOrange"
						}
						"Theme_Numbers"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Numbers"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reOrange"
						}
						"Theme_Button_Shadow"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_orange"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
						"Theme_Button_Numbers"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_alt_orange"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
//=================================================================================================================================
// YELLOW THEME
//=================================================================================================================================
					"Theme_Yellow"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Theme_Yellow"
						"xpos"							"1+117+117+117+117"
						"ypos"							"0+42"
						"zpos"							"20"
						"wide"							"115"
						"tall"							"40"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"Health_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Health_Image"
							"xpos"						"9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/shadow_yellow"
						}
						"Shadow_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Shadow_Image"
							"xpos"						"rs1-9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/health_yellow"
						}
						"Separator"
						{
							"ControlName"				"Panel"
							"fieldName"					"Separator"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"2"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Theme_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Name"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Yellow"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reYellow"
						}
						"Theme_Shadow"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Shadow"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reYellow"
						}
						"Theme_Numbers"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Numbers"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reYellow"
						}
						"Theme_Button_Shadow"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_yellow"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
						"Theme_Button_Numbers"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_alt_yellow"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
//=================================================================================================================================
// GREEN PALE THEME
//=================================================================================================================================
					"Theme_Green_Pale"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Theme_Green_Pale"
						"xpos"							"1"
						"ypos"							"0+42+42"
						"zpos"							"20"
						"wide"							"115"
						"tall"							"40"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"Health_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Health_Image"
							"xpos"						"9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/shadow_green_pale"
						}
						"Shadow_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Shadow_Image"
							"xpos"						"rs1-9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/health_green_pale"
						}
						"Separator"
						{
							"ControlName"				"Panel"
							"fieldName"					"Separator"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"2"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Theme_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Name"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Green Pale"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reGreenPale"
						}
						"Theme_Shadow"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Shadow"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reGreenPale"
						}
						"Theme_Numbers"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Numbers"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reGreenPale"
						}
						"Theme_Button_Shadow"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_greenpale"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
						"Theme_Button_Numbers"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_alt_greenpale"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
//=================================================================================================================================
// GREEN DARK THEME
//=================================================================================================================================
					"Theme_Green_Dark"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Theme_Green_Dark"
						"xpos"							"1+117"
						"ypos"							"0+42+42"
						"zpos"							"20"
						"wide"							"115"
						"tall"							"40"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"Health_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Health_Image"
							"xpos"						"9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/shadow_green_dark"
						}
						"Shadow_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Shadow_Image"
							"xpos"						"rs1-9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/health_green_dark"
						}
						"Separator"
						{
							"ControlName"				"Panel"
							"fieldName"					"Separator"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"2"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Theme_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Name"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Green Dark"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reGreenDark"
						}
						"Theme_Shadow"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Shadow"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reGreenDark"
						}
						"Theme_Numbers"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Numbers"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reGreenDark"
						}
						"Theme_Button_Shadow"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_greendark"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
						"Theme_Button_Numbers"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_alt_greendark"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
//=================================================================================================================================
// TEAL THEME
//=================================================================================================================================
					"Theme_Teal"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Theme_Teal"
						"xpos"							"1+117+117"
						"ypos"							"0+42+42"
						"zpos"							"20"
						"wide"							"115"
						"tall"							"40"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"Health_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Health_Image"
							"xpos"						"9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/shadow_teal"
						}
						"Shadow_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Shadow_Image"
							"xpos"						"rs1-9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/health_teal"
						}
						"Separator"
						{
							"ControlName"				"Panel"
							"fieldName"					"Separator"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"2"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Theme_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Name"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Teal"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reTeal"
						}
						"Theme_Shadow"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Shadow"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reTeal"
						}
						"Theme_Numbers"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Numbers"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reTeal"
						}
						"Theme_Button_Shadow"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_teal"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
						"Theme_Button_Numbers"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_alt_teal"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
//=================================================================================================================================
// BLU THEME
//=================================================================================================================================
					"Theme_Blu"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Theme_Blu"
						"xpos"							"1+117+117+117"
						"ypos"							"0+42+42"
						"zpos"							"20"
						"wide"							"115"
						"tall"							"40"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"Health_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Health_Image"
							"xpos"						"9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/shadow_blu"
						}
						"Shadow_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Shadow_Image"
							"xpos"						"rs1-9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/health_blu"
						}
						"Separator"
						{
							"ControlName"				"Panel"
							"fieldName"					"Separator"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"2"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Theme_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Name"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Blu"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reBlu"
						}
						"Theme_Shadow"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Shadow"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reBlu"
						}
						"Theme_Numbers"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Numbers"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reBlu"
						}
						"Theme_Button_Shadow"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_blu"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
						"Theme_Button_Numbers"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_alt_blu"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
//=================================================================================================================================
// VIOLET THEME
//=================================================================================================================================
					"Theme_Violet"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Theme_Violet"
						"xpos"							"1+117+117+117+117"
						"ypos"							"0+42+42"
						"zpos"							"20"
						"wide"							"115"
						"tall"							"40"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"Health_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Health_Image"
							"xpos"						"9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/shadow_violet"
						}
						"Shadow_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Shadow_Image"
							"xpos"						"rs1-9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/health_violet"
						}
						"Separator"
						{
							"ControlName"				"Panel"
							"fieldName"					"Separator"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"2"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Theme_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Name"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Violet"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reViolet"
						}
						"Theme_Shadow"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Shadow"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reViolet"
						}
						"Theme_Numbers"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Numbers"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reViolet"
						}
						"Theme_Button_Shadow"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_violet"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
						"Theme_Button_Numbers"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_alt_violet"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
//=================================================================================================================================
// PINK THEME
//=================================================================================================================================
					"Theme_Pink"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Theme_Pink"
						"xpos"							"1"
						"ypos"							"0+42+42+42"
						"zpos"							"20"
						"wide"							"115"
						"tall"							"40"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"Health_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Health_Image"
							"xpos"						"9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/shadow_pink"
						}
						"Shadow_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Shadow_Image"
							"xpos"						"rs1-9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/health_pink"
						}
						"Separator"
						{
							"ControlName"				"Panel"
							"fieldName"					"Separator"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"2"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Theme_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Name"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Pink"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0rePink"
						}
						"Theme_Shadow"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Shadow"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0rePink"
						}
						"Theme_Numbers"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Numbers"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0rePink"
						}
						"Theme_Button_Shadow"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_pink"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
						"Theme_Button_Numbers"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_alt_pink"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
//=================================================================================================================================
// MAGENTA THEME
//=================================================================================================================================
					"Theme_Magenta"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Theme_Magenta"
						"xpos"							"1+117"
						"ypos"							"0+42+42+42"
						"zpos"							"20"
						"wide"							"115"
						"tall"							"40"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"Health_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Health_Image"
							"xpos"						"9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/shadow_magenta"
						}
						"Shadow_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Shadow_Image"
							"xpos"						"rs1-9"
							"ypos"						"cs-0.5"
							"zpos"						"0"
							"wide"						"40"
							"tall"						"40"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/themes/health_magenta"
						}
						"Separator"
						{
							"ControlName"				"Panel"
							"fieldName"					"Separator"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"2"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Theme_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Name"
							"xpos"						"0"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Magenta"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reMagenta"
						}
						"Theme_Shadow"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Shadow"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reMagenta"
						}
						"Theme_Numbers"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Theme_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"p0.5"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Colored Numbers"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"m0reMagenta"
						}
						"Theme_Button_Shadow"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Shadow"
							"xpos"						"0"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_alt_magenta"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
						"Theme_Button_Numbers"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Theme_Button_Numbers"
							"xpos"						"rs1"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"p0.5"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine theme_magenta"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
				}
			}
		}
	}
}