"Resource/UI/Customizations/#Customization_Menu/HUD_Customization_TargetID.res"
{
	"SafeMode"
	{
		"Customizations_Scroller"
		{
			"HUD_TargetID_Style_Selection"
			{
				"ControlName"							"EditablePanel"
				"fieldName"								"HUD_TargetID_Style_Selection"
				"xpos"									"3"
				"ypos"									"628"
				"zpos"									"0"
				"wide"									"f12"
				"tall"									"60"
				"visible"								"1"
				"enabled"								"1"
				"proportionaltoparent"					"1"
				"paintBackground"						"1"
				"paintBackgroundType"					"0"
				"bgcolor_override"						"Black"

				"Title"
				{
					"ControlName"						"CExLabel"
					"fieldName"							"Title"
					"xpos"								"0"
					"ypos"								"0"
					"zpos"								"0"
					"wide"								"f0"
					"tall"								"14"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"use_proportional_insets"			"1"
					"labelText"							"TargetID Customization:"
					"font"								"FontStorePrice"
					"textAlignment"						"west"
					"textinsetx"						"5"
					"fgcolor"							"White"
					"paintbackground"					"1"
					"paintBackgroundType"				"0"
					"bgcolor_override"					"StoreGreen"
				}
//=================================================================================================================================
// TARGET ID HEALTH STYLE
//=================================================================================================================================
				"TargetID_HP_Style_Selection"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"TargetID_HP_Style_Selection"
					"xpos"								"2"
					"ypos"								"16"
					"zpos"								"20"
					"wide"								"194"
					"tall"								"f18"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"
					"paintbackgroundtype"				"0"
					"bgcolor_override"					"120 120 120 255"

					"TargetID_HP_Style_Label"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"TargetID_HP_Style_Label"
						"xpos"							"cs-0.5"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"f0"
						"tall"							"12"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"font"							"ItemFontNameSmallest"
						"labeltext"						"Health Style:"
						"textAlignment"					"center"
						"fgcolor"						"White"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"80 74 74 255"
					}
// HEALTH NUMBERS -------------------------------------------------------------------------------------------------------------------
					"TargetID_HP_Numbers"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"TargetID_HP_Numbers"
						"xpos"							"0"
						"ypos"							"rs1"
						"zpos"							"1"
						"wide"							"96"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"TargetID_HP_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"TargetID_HP_Name"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Health Numbers"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"FooterBGBlack"
						}
						"TargetID_HP_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"TargetID_HP_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-2"
							"zpos"						"0"
							"wide"						"90"
							"tall"						"45"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/targetid/targetid_normal"
						}
						"TargetID_HP_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"TargetID_HP_Button"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_targetid_numbers"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
					"Separator1"
					{
						"ControlName"					"Panel"
						"fieldName"						"Separator1"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"2"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"FooterBGBlack"

						"pin_to_sibling"				"TargetID_HP_Numbers"
						"pin_corner_to_sibling"			"PIN_BOTTOMLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMRIGHT"
					}
// HEALTH CROSS -----------------------------------------------------------------------------------------------------------------
					"TargetID_HP_Cross"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"TargetID_HP_Cross"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"96"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"pin_to_sibling"				"Separator1"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"TargetID_HP_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"TargetID_HP_Name"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Health Cross"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"FooterBGBlack"
						}
						"TargetID_HP_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"TargetID_HP_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-2"
							"zpos"						"0"
							"wide"						"90"
							"tall"						"45"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/targetid/targetid_cross"
						}
						"TargetID_HP_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"TargetID_HP_Button"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_targetid_cross"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
				}
//=================================================================================================================================
// TARGET ID MEDIGUN NAMING STYLE
//=================================================================================================================================
				"TargetID_Medigun_Style_Selection"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"TargetID_Medigun_Style_Selection"
					"xpos"								"2"
					"ypos"								"0"
					"zpos"								"20"
					"wide"								"194"
					"tall"								"f18"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"
					"paintbackgroundtype"				"0"
					"bgcolor_override"					"120 120 120 255"

					"pin_to_sibling"					"TargetID_HP_Style_Selection"
					"pin_corner_to_sibling"				"PIN_TOPLEFT"
					"pin_to_sibling_corner"				"PIN_TOPRIGHT"

					"TargetID_Medigun_Style_Label"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"TargetID_Medigun_Style_Label"
						"xpos"							"cs-0.5"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"f0"
						"tall"							"12"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"font"							"ItemFontNameSmallest"
						"labeltext"						"Medigun Name Style:"
						"textAlignment"					"center"
						"fgcolor"						"White"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"80 74 74 255"
					}
// MEDIGUN NAMES ---------------------------------------------------------------------------------------------------------------------------
					"TargetID_Medigun_Names"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"TargetID_Medigun_Names"
						"xpos"							"0"
						"ypos"							"rs1"
						"zpos"							"1"
						"wide"							"96"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"TargetID_Medigun_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"TargetID_Medigun_Name"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Medigun Names"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"FooterBGBlack"
						}
						"TargetID_Medigun_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"TargetID_Medigun_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-2"
							"zpos"						"0"
							"wide"						"90"
							"tall"						"45"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/targetid/targetid_normal"
						}
						"TargetID_Medigun_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"TargetID_Medigun_Button"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_targetid_uber_clear"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
					"Separator1"
					{
						"ControlName"					"Panel"
						"fieldName"						"Separator1"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"2"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"FooterBGBlack"

						"pin_to_sibling"				"TargetID_Medigun_Names"
						"pin_corner_to_sibling"			"PIN_BOTTOMLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMRIGHT"
					}
// MEDIGUN ICONS -----------------------------------------------------------------------------------------------------------------
					"TargetID_Medigun_Icons"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"TargetID_Medigun_Icons"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"96"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"pin_to_sibling"				"Separator1"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"TargetID_Medigun_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"TargetID_Medigun_Name"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Medigun Icons"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"FooterBGBlack"
						}
						"TargetID_Medigun_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"TargetID_Medigun_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-2"
							"zpos"						"0"
							"wide"						"66"
							"tall"						"33"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/targetid/targetid_icons"
						}
						"TargetID_Medigun_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"TargetID_Medigun_Button"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_targetid_icons"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
				}
//=================================================================================================================================
// TARGET ID BACKGROUND STYLE
//=================================================================================================================================
				"TargetID_Background_Style_Selection"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"TargetID_Background_Style_Selection"
					"xpos"								"2"
					"ypos"								"0"
					"zpos"								"20"
					"wide"								"192"
					"tall"								"f18"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"
					"paintbackgroundtype"				"0"
					"bgcolor_override"					"120 120 120 255"

					"pin_to_sibling"					"TargetID_Medigun_Style_Selection"
					"pin_corner_to_sibling"				"PIN_TOPLEFT"
					"pin_to_sibling_corner"				"PIN_TOPRIGHT"

					"TargetID_Background_Style_Label"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"TargetID_Background_Style_Label"
						"xpos"							"cs-0.5"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"f0"
						"tall"							"12"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"font"							"ItemFontNameSmallest"
						"labeltext"						"Background Style:"
						"textAlignment"					"center"
						"fgcolor"						"White"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"80 74 74 255"
					}
// BACKGROUND ON ---------------------------------------------------------------------------------------------------------------------------
					"TargetID_Background_ON"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"TargetID_Background_ON"
						"xpos"							"0"
						"ypos"							"rs1"
						"zpos"							"1"
						"wide"							"95"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"TargetID_Background_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"TargetID_Background_Name"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Background ON"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"FooterBGBlack"
						}
						"TargetID_Background_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"TargetID_Background_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-2"
							"zpos"						"0"
							"wide"						"90"
							"tall"						"45"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/targetid/targetid_normal"
						}
						"TargetID_Background_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"TargetID_Background_Button"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_targetid_bg_clear"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
					"Separator1"
					{
						"ControlName"					"Panel"
						"fieldName"						"Separator1"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"2"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"FooterBGBlack"

						"pin_to_sibling"				"TargetID_Background_ON"
						"pin_corner_to_sibling"			"PIN_BOTTOMLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMRIGHT"
					}
// BACKGROUND OFF -----------------------------------------------------------------------------------------------------------------
					"TargetID_Background_OFF"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"TargetID_Background_OFF"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"96"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"pin_to_sibling"				"Separator1"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"TargetID_Background_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"TargetID_Background_Name"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Background OFF"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"FooterBGBlack"
						}
						"TargetID_Background_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"TargetID_Background_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-2"
							"zpos"						"0"
							"wide"						"90"
							"tall"						"45"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/targetid/targetid_bg_off"
						}
						"TargetID_Background_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"TargetID_Background_Button"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"f1"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine m0_targetid_bg_off"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
				}
			}
		}
	}
}