"Resource/UI/Customizations/#Customization_Menu/HUD_Customization_Damage.res"
{
	"SafeMode"
	{
		"Customizations_Scroller"
		{
			"HUD_Damage_Style_Selection"
			{
				"ControlName"							"EditablePanel"
				"fieldName"								"HUD_Damage_Style_Selection"
				"xpos"									"2"
				"ypos"									"374"
				"zpos"									"0"
				"wide"									"f8"
				"tall"									"70"
				"visible"								"1"
				"enabled"								"1"
				"proportionaltoparent"					"1"
				"paintBackground"						"1"
				"paintBackgroundType"					"2"
				"roundedcorners"						"3"
				"bgcolor_override"						"FooterBGBlack"

				"Title"
				{
					"ControlName"						"CExLabel"
					"fieldName"							"Title"
					"xpos"								"0"
					"ypos"								"0"
					"zpos"								"0"
					"wide"								"f0"
					"tall"								"14"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"use_proportional_insets"			"1"
					"labelText"							"Damage Style:"
					"font"								"ItemFontNameSmallest"
					"textAlignment"						"west"
					"textinsetx"						"5"
					"fgcolor"							"White"
					"paintbackground"					"1"
					"paintBackgroundType"				"2"
					"roundedcorners"					"3"
					"bgcolor_override"					"StoreGreen"
				}
//=================================================================================================================================
// FLOATING DAMAGE STYLE
//=================================================================================================================================
				"Floating_Damage_Style_Selection"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Floating_Damage_Style_Selection"
					"xpos"								"2"
					"ypos"								"16"
					"zpos"								"20"
					"wide"								"327"
					"tall"								"f18"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"
					"paintbackgroundtype"				"0"
					"bgcolor_override"					"120 120 120 255"

					"Floating_Damage_Style_Label"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Floating_Damage_Style_Label"
						"xpos"							"cs-0.5"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"f0"
						"tall"							"12"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"font"							"ItemFontNameSmallest"
						"labeltext"						"Floating Damage Style:"
						"textAlignment"					"center"
						"fgcolor"						"White"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"80 74 74 255"
					}
// SMALL ---------------------------------------------------------------------------------------------------------------------------
					"Damage_Small"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Damage_Small"
						"xpos"							"0"
						"ypos"							"rs1"
						"zpos"							"1"
						"wide"							"51"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"Damage_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Damage_Name"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Small"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Damage_Example"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Damage_Example"
							"xpos"						"cs-0.5"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"wrap"						"1"
							"centerwrap"				"1"
							"font"						"Showcase_Damage_Small"
							"labeltext"					"-120"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"120 120 120 255"
						}
						"Damage_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Damage_Button"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine damage_small"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
					"Separator1"
					{
						"ControlName"					"Panel"
						"fieldName"						"Separator1"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"2"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"Black"

						"pin_to_sibling"				"Damage_Small"
						"pin_corner_to_sibling"			"PIN_BOTTOMLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMRIGHT"
					}
// SMALL MINUSLESS -----------------------------------------------------------------------------------------------------------------
					"Damage_Small_Minusless"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Damage_Small_Minusless"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"52"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"pin_to_sibling"				"Separator1"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Damage_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Damage_Name"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Small, No -"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Damage_Example"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Damage_Example"
							"xpos"						"cs-0.5"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"wrap"						"1"
							"centerwrap"				"1"
							"font"						"Showcase_Damage_Small"
							"labeltext"					"120"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"120 120 120 255"
						}
						"Damage_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Damage_Button"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine damage_small_minusless"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
					"Separator2"
					{
						"ControlName"					"Panel"
						"fieldName"						"Separator2"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"2"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"Black"

						"pin_to_sibling"				"Damage_Small_Minusless"
						"pin_corner_to_sibling"			"PIN_BOTTOMLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMRIGHT"
					}
// MEDIUM -------------------------------------------------------------------------------------------------------------------------
					"Damage_Medium"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Damage_Medium"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"54"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"pin_to_sibling"				"Separator2"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Damage_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Damage_Name"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Medium"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Damage_Example"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Damage_Example"
							"xpos"						"cs-0.5"
							"ypos"						"-1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"wrap"						"1"
							"centerwrap"				"1"
							"font"						"Showcase_Damage_Medium"
							"labeltext"					"-120"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"120 120 120 255"
						}
						"Damage_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Damage_Button"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine damage_medium"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
					"Separator3"
					{
						"ControlName"					"Panel"
						"fieldName"						"Separator3"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"2"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"Black"

						"pin_to_sibling"				"Damage_Medium"
						"pin_corner_to_sibling"			"PIN_BOTTOMLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMRIGHT"
					}
// MEDIUM MINUSLESS ----------------------------------------------------------------------------------------------------------------
					"Damage_Medium_Minusless"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Damage_Medium_Minusless"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"54"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"pin_to_sibling"				"Separator3"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Damage_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Damage_Name"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Medium, No -"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Damage_Example"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Damage_Example"
							"xpos"						"cs-0.5"
							"ypos"						"-1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"wrap"						"1"
							"centerwrap"				"1"
							"font"						"Showcase_Damage_Medium"
							"labeltext"					"120"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"120 120 120 255"
						}
						"Damage_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Damage_Button"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine damage_medium_minusless"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
					"Separator4"
					{
						"ControlName"					"Panel"
						"fieldName"						"Separator4"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"2"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"Black"

						"pin_to_sibling"				"Damage_Medium_Minusless"
						"pin_corner_to_sibling"			"PIN_BOTTOMLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMRIGHT"
					}
// BIG ----------------------------------------------------------------------------------------------------------------------------
					"Damage_Big"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Damage_Big"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"54"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"pin_to_sibling"				"Separator4"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Damage_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Damage_Name"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Big"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Damage_Example"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Damage_Example"
							"xpos"						"cs-0.5"
							"ypos"						"-2"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"wrap"						"1"
							"centerwrap"				"1"
							"font"						"Showcase_Damage_Big"
							"labeltext"					"-120"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"120 120 120 255"
						}
						"Damage_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Damage_Button"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine damage_big"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
					"Separator5"
					{
						"ControlName"					"Panel"
						"fieldName"						"Separator5"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"2"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"Black"

						"pin_to_sibling"				"Damage_Big"
						"pin_corner_to_sibling"			"PIN_BOTTOMLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMRIGHT"
					}
// BIG MINUSLESS ------------------------------------------------------------------------------------------------------------------
					"Damage_Big_Minusless"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Damage_Big_Minusless"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"54"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"pin_to_sibling"				"Separator5"
						"pin_corner_to_sibling"			"PIN_TOPLEFT"
						"pin_to_sibling_corner"			"PIN_TOPRIGHT"

						"Damage_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Damage_Name"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Big, No -"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Damage_Example"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Damage_Example"
							"xpos"						"cs-0.5"
							"ypos"						"-2"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"wrap"						"1"
							"centerwrap"				"1"
							"font"						"Showcase_Damage_Big"
							"labeltext"					"120"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"120 120 120 255"
						}
						"Damage_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Damage_Button"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine damage_big_minusless"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
				}
//=================================================================================================================================
// LAST DAMAGE DONE STYLE
//=================================================================================================================================
				"Last_Damage_Done_Style_Selection"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Last_Damage_Done_Style_Selection"
					"xpos"								"2"
					"ypos"								"0"
					"zpos"								"20"
					"wide"								"258"
					"tall"								"f18"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"
					"paintbackgroundtype"				"0"
					"bgcolor_override"					"120 120 120 255"

					"pin_to_sibling"					"Floating_Damage_Style_Selection"
					"pin_corner_to_sibling"				"PIN_TOPLEFT"
					"pin_to_sibling_corner"				"PIN_TOPRIGHT"

					"Last_Damage_Done_Style_Label"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Last_Damage_Done_Style_Label"
						"xpos"							"cs-0.5"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"f0"
						"tall"							"12"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"font"							"ItemFontNameSmallest"
						"labeltext"						"Last Damage Done Style:"
						"textAlignment"					"center"
						"fgcolor"						"White"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"80 74 74 255"
					}
// OFF ---------------------------------------------------------------------------------------------------------------------------
					"Last_Damage_OFF"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Last_Damage_OFF"
						"xpos"							"0"
						"ypos"							"rs1"
						"zpos"							"1"
						"wide"							"48"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"Damage_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Damage_Name"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"OFF"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Damage_OFF_Label"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Damage_OFF_Label"
							"xpos"						"cs-0.5"
							"ypos"						"0"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"f7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"ItemFontNameSmallest"
							"labeltext"					"DISABLED"
							"textAlignment"				"center"
							"fgcolor"					"Black"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Red"
						}
						"Damage_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Damage_Button"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine last_damage_off"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
					"Separator1"
					{
						"ControlName"					"Panel"
						"fieldName"						"Separator1"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"2"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"Black"

						"pin_to_sibling"				"Last_Damage_OFF"
						"pin_corner_to_sibling"			"PIN_BOTTOMLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMRIGHT"
					}
// HEALTH ---------------------------------------------------------------------------------------------------------------------------
					"Last_Damage_Health"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Last_Damage_Health"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"51"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"pin_to_sibling"				"Separator1"
						"pin_corner_to_sibling"			"PIN_BOTTOMLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMRIGHT"

						"Damage_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Damage_Name"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Above Health"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Damage_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Damage_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-3"
							"zpos"						"0"
							"wide"						"44"
							"tall"						"44"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/damage/last_damage_on"
						}
						"Damage_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Damage_Button"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine last_damage_health"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
					"Separator2"
					{
						"ControlName"					"Panel"
						"fieldName"						"Separator2"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"2"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"Black"

						"pin_to_sibling"				"Last_Damage_Health"
						"pin_corner_to_sibling"			"PIN_BOTTOMLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMRIGHT"
					}
// CROSS ---------------------------------------------------------------------------------------------------------------------------
					"Last_Damage_Cross"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Last_Damage_Cross"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"51"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"pin_to_sibling"				"Separator2"
						"pin_corner_to_sibling"			"PIN_BOTTOMLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMRIGHT"

						"Damage_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Damage_Name"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Cross"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Damage_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Damage_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-4"
							"zpos"						"0"
							"wide"						"44"
							"tall"						"44"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/damage/last_damage_cross"
						}
						"Damage_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Damage_Button"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine last_damage_cross"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
					"Separator3"
					{
						"ControlName"					"Panel"
						"fieldName"						"Separator3"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"2"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"Black"

						"pin_to_sibling"				"Last_Damage_Cross"
						"pin_corner_to_sibling"			"PIN_BOTTOMLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMRIGHT"
					}
// AMMO ---------------------------------------------------------------------------------------------------------------------------
					"Last_Damage_Ammo"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Last_Damage_Ammo"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"51"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"pin_to_sibling"				"Separator3"
						"pin_corner_to_sibling"			"PIN_BOTTOMLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMRIGHT"

						"Damage_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Damage_Name"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Above Ammo"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Damage_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Damage_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-3"
							"zpos"						"0"
							"wide"						"32"
							"tall"						"32"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/damage/last_damage_ammo"
						}
						"Damage_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Damage_Button"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine last_damage_ammo"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
					"Separator4"
					{
						"ControlName"					"Panel"
						"fieldName"						"Separator4"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"2"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"Black"

						"pin_to_sibling"				"Last_Damage_Ammo"
						"pin_corner_to_sibling"			"PIN_BOTTOMLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMRIGHT"
					}
// CENTER ---------------------------------------------------------------------------------------------------------------------------
					"Last_Damage_Center"
					{
						"ControlName"					"EditablePanel"
						"fieldName"						"Last_Damage_Center"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"51"
						"tall"							"f12"
						"visible"						"1"
						"enabled"						"1"
						"proportionaltoparent"			"1"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"120 120 120 255"

						"pin_to_sibling"				"Separator4"
						"pin_corner_to_sibling"			"PIN_BOTTOMLEFT"
						"pin_to_sibling_corner"			"PIN_BOTTOMRIGHT"

						"Damage_Name"
						{
							"ControlName"				"CExLabel"
							"fieldName"					"Damage_Name"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"1"
							"wide"						"f0"
							"tall"						"7"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"proportionaltoparent"		"1"
							"font"						"DefaultVerySmall"
							"labeltext"					"Centered"
							"textAlignment"				"center"
							"fgcolor"					"White"
							"paintbackground"			"1"
							"paintbackgroundtype"		"0"
							"bgcolor_override"			"Black"
						}
						"Damage_Image"
						{
							"ControlName"				"ImagePanel"
							"fieldName"					"Damage_Image"
							"xpos"						"cs-0.5"
							"ypos"						"cs-0.5-4"
							"zpos"						"0"
							"wide"						"37"
							"tall"						"37"
							"visible"					"1"
							"enabled"					"1"
							"mouseinputenabled"			"0"
							"scaleImage"				"1"
							"proportionaltoparent"		"1"
							"image"						"replay/thumbnails/customizations/damage/last_damage_center"
						}
						"Damage_Button"
						{
							"ControlName"				"CExButton"
							"fieldName"					"Damage_Button"
							"xpos"						"cs-0.5"
							"ypos"						"rs1"
							"zpos"						"5"
							"wide"						"f0"
							"tall"						"f0"
							"visible"					"1"
							"enabled"					"1"
							"font"						""
							"command"					"engine last_damage_center"
							"labeltext"					""
							"sound_depressed"			"UI/buttonclick.wav"
							"proportionaltoparent"		"1"
							"actionsignallevel"			"6"

							"paintbackground"			"0"
							"paintborder"				"1"

							"border_default"			"NoBorder"
							"border_armed"				"BorderSelectionWhite"

							"defaultFgColor_override"	"White"
							"armedFgColor_override"		"White"
							"depressedFgColor_override"	"White"
						}
					}
				}
			}
		}
	}
}