"Resource/UI/Customizations/#Customization_Menu/HUD_Customization_Ammo.res"
{
	"SafeMode"
	{
		"Customizations_Scroller"
		{
			"HUD_Ammo_Selection"
			{
				"ControlName"							"EditablePanel"
				"fieldName"								"HUD_Ammo_Selection"
				"xpos"									"rs1-9"
				"ypos"									"332"
				"zpos"									"0"
				"wide"									"113"
				"tall"									"70"
				"visible"								"1"
				"enabled"								"1"
				"proportionaltoparent"					"1"
				"paintBackground"						"1"
				"paintBackgroundType"					"0"
				"bgcolor_override"						"Black"

				"Title"
				{
					"ControlName"						"CExLabel"
					"fieldName"							"Title"
					"xpos"								"0"
					"ypos"								"0"
					"zpos"								"0"
					"wide"								"f0"
					"tall"								"14"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"use_proportional_insets"			"1"
					"labelText"							"Ammo Customization:"
					"font"								"FontStorePrice"
					"textAlignment"						"west"
					"textinsetx"						"5"
					"fgcolor"							"White"
					"paintbackground"					"1"
					"paintBackgroundType"				"0"
					"bgcolor_override"					"StoreGreen"
				}
// STATIC ANIMATION ----------------------------------------------------------------------------------------------------------------------
				"Low_Ammo_Static"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Low_Ammo_Static"
					"xpos"								"2"
					"ypos"								"rs1-2"
					"zpos"								"20"
					"wide"								"54"
					"tall"								"f18"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"
					"paintbackgroundtype"				"0"
					"bgcolor_override"					"120 120 120 255"

					"Low_Ammo_Name"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Low_Ammo_Name"
						"xpos"							"cs-0.5"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"f0"
						"tall"							"12"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"font"							"ItemFontNameSmallest"
						"labeltext"						"Static"
						"textAlignment"					"center"
						"fgcolor"						"White"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"80 74 74 255"
					}
					"Low_Ammo_Image"
					{
						"ControlName"					"ImagePanel"
						"fieldName"						"Low_Ammo_Image"
						"xpos"							"cs-0.5"
						"ypos"							"rs1-4"
						"zpos"							"0"
						"wide"							"35"
						"tall"							"35"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"scaleImage"					"1"
						"proportionaltoparent"			"1"
						"image"							"replay/thumbnails/customizations/ammo/ammo_low"
					}
					"Low_Ammo_Button"
					{
						"ControlName"					"CExButton"
						"fieldName"						"Low_Ammo_Button"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"5"
						"wide"							"f0"
						"tall"							"f0"
						"visible"						"1"
						"enabled"						"1"
						"font"							""
						"command"						"engine m0_low_ammo_style_clear"
						"labeltext"						""
						"sound_depressed"				"UI/buttonclick.wav"
						"proportionaltoparent"			"1"
						"actionsignallevel"				"5"

						"paintbackground"				"0"
						"paintborder"					"1"

						"border_default"				"NoBorder"
						"border_armed"					"BorderSelectionWhite"

						"defaultFgColor_override"		"White"
						"armedFgColor_override"			"White"
						"depressedFgColor_override"		"White"
					}
				}
// FLASHING ANIMATION -------------------------------------------------------------------------------------------------------------------
				"Low_Ammo_Flash"
				{
					"ControlName"						"EditablePanel"
					"fieldName"							"Low_Ammo_Flash"
					"xpos"								"2"
					"ypos"								"0"
					"zpos"								"20"
					"wide"								"54"
					"tall"								"f18"
					"visible"							"1"
					"enabled"							"1"
					"proportionaltoparent"				"1"
					"paintbackground"					"1"
					"paintbackgroundtype"				"0"
					"bgcolor_override"					"120 120 120 255"

					"pin_to_sibling"					"Low_Ammo_Static"
					"pin_corner_to_sibling"				"PIN_TOPLEFT"
					"pin_to_sibling_corner"				"PIN_TOPRIGHT"

					"Low_Ammo_Name"
					{
						"ControlName"					"CExLabel"
						"fieldName"						"Low_Ammo_Name"
						"xpos"							"cs-0.5"
						"ypos"							"0"
						"zpos"							"1"
						"wide"							"f0"
						"tall"							"12"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"proportionaltoparent"			"1"
						"font"							"ItemFontNameSmallest"
						"labeltext"						"Flashing"
						"textAlignment"					"center"
						"fgcolor"						"White"
						"paintbackground"				"1"
						"paintbackgroundtype"			"0"
						"bgcolor_override"				"80 74 74 255"
					}
					"Low_Ammo_Image"
					{
						"ControlName"					"ImagePanel"
						"fieldName"						"Low_Ammo_Image"
						"xpos"							"cs-0.5"
						"ypos"							"rs1-4"
						"zpos"							"0"
						"wide"							"35"
						"tall"							"35"
						"visible"						"1"
						"enabled"						"1"
						"mouseinputenabled"				"0"
						"scaleImage"					"1"
						"proportionaltoparent"			"1"
						"image"							"replay/thumbnails/customizations/ammo/ammo_flash"
					}
					"Low_Ammo_Button"
					{
						"ControlName"					"CExButton"
						"fieldName"						"Low_Ammo_Button"
						"xpos"							"0"
						"ypos"							"0"
						"zpos"							"5"
						"wide"							"f0"
						"tall"							"f0"
						"visible"						"1"
						"enabled"						"1"
						"font"							""
						"command"						"engine m0_ammo_flash_animation"
						"labeltext"						""
						"sound_depressed"				"UI/buttonclick.wav"
						"proportionaltoparent"			"1"
						"actionsignallevel"				"5"

						"paintbackground"				"0"
						"paintborder"					"1"

						"border_default"				"NoBorder"
						"border_armed"					"BorderSelectionWhite"

						"defaultFgColor_override"		"White"
						"armedFgColor_override"			"White"
						"depressedFgColor_override"		"White"
					}
				}
			}
		}
	}
}