"Resource/UI/HudArenaPlayerCount.res"
{
	"BlueTeam"
	{
		"ControlName"								"EditablePanel"
		"FieldName"									"BlueTeam"
		"XPos"										"cs-1.2"
		"YPos"										"2"
		"ZPos"										"0"
		"Wide"										"25"
		"Tall"										"25"
		"Visible"									"1"

		"Count"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"Count"
			"XPos"									"0"
			"YPos"									"0"
			"ZPos"									"2"
			"Wide"									"f0"
			"Tall"									"f0"
			"Visible"								"1"
			"Enabled"								"1"
			"ProportionalToParent"					"1"
			"Font"									"m0refont20"
			"LabelText"								"%blue_alive%"
			"TextAlignment"							"center"
			"FGColor"								"HUDBlueTeamSolid"
		}
		"CountShadow"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"CountShadow"
			"XPos"									"-1"
			"YPos"									"-1"
			"ZPos"									"2"
			"Wide"									"f0"
			"Tall"									"f0"
			"Visible"								"1"
			"Enabled"								"1"
			"ProportionalToParent"					"1"
			"Font"									"m0refont20"
			"LabelText"								"%blue_alive%"
			"TextAlignment"							"center"
			"FGColor"								"Black"

			"Pin_To_Sibling"						"Count"
		}
		"Background"
		{
			"ControlName"							"CTFImagePanel"
			"FieldName"								"Background"
			"XPos"									"9999"
			"YPos"									"9999"
			"Wide"									"0"
			"Tall"									"0"
			"Visible"								"0"
			"Enabled"								"0"
		}
		"PlayerImage"
		{
			"ControlName"							"ImagePanel"
			"FieldName"								"PlayerImage"
			"XPos"									"9999"
			"YPos"									"9999"
			"Wide"									"0"
			"Tall"									"0"
			"Visible"								"0"
			"Enabled"								"0"
		}
	}
	"RedTeam"
	{
		"ControlName"								"EditablePanel"
		"FieldName"									"RedTeam"
		"XPos"										"cs+0.2"
		"YPos"										"2"
		"ZPos"										"0"
		"Wide"										"25"
		"Tall"										"25"
		"Visible"									"1"

		"Count"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"Count"
			"XPos"									"0"
			"YPos"									"0"
			"ZPos"									"2"
			"Wide"									"f0"
			"Tall"									"f0"
			"Visible"								"1"
			"Enabled"								"1"
			"ProportionalToParent"					"1"
			"Font"									"m0refont20"
			"LabelText"								"%red_alive%"
			"TextAlignment"							"center"
			"FGColor"								"HUDRedTeamSolid"
		}
		"CountShadow"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"CountShadow"
			"XPos"									"-1"
			"YPos"									"-1"
			"ZPos"									"2"
			"Wide"									"f0"
			"Tall"									"f0"
			"Visible"								"1"
			"Enabled"								"1"
			"ProportionalToParent"					"1"
			"Font"									"m0refont20"
			"LabelText"								"%red_alive%"
			"TextAlignment"							"center"
			"FGColor"								"Black"

			"Pin_To_Sibling"						"Count"
		}
		"Background"
		{
			"ControlName"							"CTFImagePanel"
			"FieldName"								"Background"
			"XPos"									"9999"
			"YPos"									"9999"
			"Wide"									"0"
			"Tall"									"0"
			"Visible"								"0"
			"Enabled"								"0"
		}
		"PlayerImage"
		{
			"ControlName"							"ImagePanel"
			"FieldName"								"PlayerImage"
			"XPos"									"9999"
			"YPos"									"9999"
			"Wide"									"0"
			"Tall"									"0"
			"Visible"								"0"
			"Enabled"								"0"
		}
	}
}