"Resource/UI/HudArenaClassLayout.res"
{
	"LocalPlayerBG"
	{
		"ControlName"								"CTFImagePanel"
		"fieldName"									"LocalPlayerBG"
		"xpos"										"0"
		"ypos"										"135"
		"zpos"										"2"
		"wide"										"25"
		"tall"										"45"
		"visible"									"1"
		"enabled"									"1"

		"image"										"../hud/color_panel_clear"
		"scaleImage"								"1"
		"teambg_2"									"../hud/color_panel_clear"
		"teambg_3"									"../hud/color_panel_clear"

		"src_corner_height"							"23"
		"src_corner_width"							"23"
		"draw_corner_width"							"5"
		"draw_corner_height"						"5"
	}
	"Title"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"Title"
		"xpos"										"cs-0.5"
		"ypos"										"112"
		"zpos"										"6"
		"wide"										"f0"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"font"										"m0refont18"
		"labelText"									"#TF_Arena_Team_Layout"
		"textAlignment"								"center"
		"fgcolor"									"White"
		"proportionaltoparent"						"1"
	}
	"TitleShadow"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"TitleShadow"
		"xpos"										"-1"
		"ypos"										"-1"
		"zpos"										"5"
		"wide"										"f0"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"font"										"m0refont18"
		"labelText"									"#TF_Arena_Team_Layout"
		"textAlignment"								"center"
		"fgcolor"									"Black"

		"pin_to_sibling"							"title"
	}
	"ClassImage0"
	{
		"ControlName"								"CTFImagePanel"
		"fieldName"									"ClassImage0"
		"xpos"										"0"
		"ypos"										"125"
		"zpos"										"3"
		"wide"										"25"
		"tall"										"50"
		"visible"									"0"
		"enabled"									"1"
		"image"										""
		"scaleImage"								"1"
	}
	"ClassImage1"
	{
		"ControlName"								"CTFImagePanel"
		"fieldName"									"ClassImage1"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"3"
		"wide"										"25"
		"tall"										"50"
		"visible"									"0"
		"enabled"									"1"
		"image"										""
		"scaleImage"								"1"
	}
	"ClassImage2"
	{
		"ControlName"								"CTFImagePanel"
		"fieldName"									"ClassImage2"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"3"
		"wide"										"25"
		"tall"										"50"
		"visible"									"0"
		"enabled"									"1"
		"image"										""
		"scaleImage"								"1"
	}
	"ClassImage3"
	{
		"ControlName"								"CTFImagePanel"
		"fieldName"									"ClassImage3"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"3"
		"wide"										"25"
		"tall"										"50"
		"visible"									"0"
		"enabled"									"1"
		"image"										""
		"scaleImage"								"1"
	}
	"ClassImage4"
	{
		"ControlName"								"CTFImagePanel"
		"fieldName"									"ClassImage4"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"3"
		"wide"										"25"
		"tall"										"50"
		"visible"									"0"
		"enabled"									"1"
		"image"										""
		"scaleImage"								"1"
	}
	"ClassImage5"
	{
		"ControlName"								"CTFImagePanel"
		"fieldName"									"ClassImage5"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"3"
		"wide"										"25"
		"tall"										"50"
		"visible"									"0"
		"enabled"									"1"
		"image"										""
		"scaleImage"								"1"
	}
	"ClassImage6"
	{
		"ControlName"								"CTFImagePanel"
		"fieldName"									"ClassImage6"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"3"
		"wide"										"25"
		"tall"										"50"
		"visible"									"0"
		"enabled"									"1"
		"image"										""
		"scaleImage"								"1"
	}
	"ClassImage7"
	{
		"ControlName"								"CTFImagePanel"
		"fieldName"									"ClassImage7"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"3"
		"wide"										"25"
		"tall"										"50"
		"visible"									"0"
		"enabled"									"1"
		"image"										""
		"scaleImage"								"1"
	}
	"ClassImage8"
	{
		"ControlName"								"CTFImagePanel"
		"fieldName"									"ClassImage8"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"3"
		"wide"										"25"
		"tall"										"50"
		"visible"									"0"
		"enabled"									"1"
		"image"										""
		"scaleImage"								"1"
	}
	"ClassImage9"
	{
		"ControlName"								"CTFImagePanel"
		"fieldName"									"ClassImage9"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"3"
		"wide"										"25"
		"tall"										"50"
		"visible"									"0"
		"enabled"									"1"
		"image"										""
		"scaleImage"								"1"
	}
	"ClassImage10"
	{
		"ControlName"								"CTFImagePanel"
		"fieldName"									"ClassImage10"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"3"
		"wide"										"25"
		"tall"										"50"
		"visible"									"0"
		"enabled"									"1"
		"image"										""
		"scaleImage"								"1"
	}
	"ClassImage11"
	{
		"ControlName"								"CTFImagePanel"
		"fieldName"									"ClassImage11"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"3"
		"wide"										"25"
		"tall"										"50"
		"visible"									"0"
		"enabled"									"1"
		"image"										""
		"scaleImage"								"1"
	}



	//==================================================================================================================================================
	// REMOVED ELEMENTS
	//==================================================================================================================================================

	"background"
	{
		"ControlName"								"CTFImagePanel"
		"fieldName"									"background"
		"xpos"										"9999"
		"ypos"										"9999"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
		"enabled"									"0"
	}
	"ChangeLabel"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"ChangeLabel"
		"xpos"										"9999"
		"ypos"										"9999"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
		"enabled"									"0"
	}
	"ChangeLabelShadow"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"ChangeLabelShadow"
		"xpos"										"9999"
		"ypos"										"9999"
		"wide"										"0"
		"tall"										"0"
		"visible"									"0"
		"enabled"									"0"
	}
}