"Resource/UI/HudMannVsMachineStatus.res"
{
	"WaveStatusPanel"
	{
		"ControlName"								"CWaveStatusPanel"
		"FieldName"									"WaveStatusPanel"
		"XPos"										"cs-0.5"
		"YPos"										"0"
		"ZPos"										"0"
		"Wide"										"600"
		"Tall"										"67"
		"Visible"									"1"
		"Enabled"									"1"
		"ProportionalToParent"						"1"
	}
	"WaveCompleteSummaryPanel"
	{
		"ControlName"								"CWaveCompleteSummaryPanel"
		"FieldName"									"WaveCompleteSummaryPanel"
		"XPos"										"c-90"
		"YPos"										"140"
		"ZPos"										"0"
		"Wide"										"180"
		"Tall"										"400"
		"Visible"									"1"
		"Enabled"									"1"
	}
	"BossStatusPanel"
	{
		"ControlName"								"CMvMBossStatusPanel"
		"FieldName"									"BossStatusPanel"
		"XPos"										"0"
		"YPos"										"0"
		"ZPos"										"0"
		"Wide"										"200"
		"Tall"										"100"
		"Visible"									"1"
		"Enabled"									"1"

		"Pin_To_Sibling"							"WaveStatusPanel"
		"Pin_Corner_To_Sibling"						"PIN_CENTER_TOP"
		"Pin_To_Sibling_Corner"						"PIN_CENTER_BOTTOM"
	}
	"InWorldCurrencyPanel"
	{
		"ControlName"								"CInWorldCurrencyStatus"
		"FieldName"									"InWorldCurrencyPanel"
		"XPos"										"c1"
		"YPos"										"rs1"
		"Wide"										"44"
		"Tall"										"12"
		"Visible"									"1"
		"Enabled"									"1"
	}
	"WarningSwoop"
	{
		"ControlName"								"CWarningSwoop"
		"FieldName"									"WarningSwoop"
		"XPos"										"c-12"
		"YPos"										"0"
		"ZPos"										"10"
		"Wide"										"24"
		"Tall"										"220"
		"Visible"									"0"
		"Enabled"									"1"
		"Image"										"../sprites/obj_icons/warning_highlight"
		"ScaleImage"								"1"
		"time"										"0.3"
	}
	"UpgradeLevelContainer"
	{
		"ControlName"								"EditablePanel"
		"FieldName"									"UpgradeLevelContainer"
		"XPos"										"0"
		"YPos"										"0"
		"Wide"										"f0"
		"Tall"										"f0"
		"Visible"									"0"
		"ProportionalToParent"						"1"

		"UpgradeProgressTrack"
		{
			"ControlName"							"CMvMBombCarrierProgress"
			"FieldName"								"UpgradeProgressTrack"
			"XPos"									"cs-0.5"
			"YPos"									"rs1"
			"Wide"									"120"
			"Tall"									"40"
			"Visible"								"1"
		}
		"UpgradeLevel1"
		{
			"ControlName"							"ImagePanel"
			"FieldName"								"UpgradeLevel1"
			"XPos"									"c-12"
			"YPos"									"r24"
			"ZPos"									"1"
			"Wide"									"8"
			"Tall"									"8"
			"Visible"								"1"
			"Enabled"								"1"
			"Image"									"../hud/hud_mvm_bomb_upgrade_1_disabled"
			"ScaleImage"							"1"
		}
		"UpgradeLevel2"
		{
			"ControlName"							"ImagePanel"
			"FieldName"								"UpgradeLevel2"
			"XPos"									"c10"
			"YPos"									"r24"
			"ZPos"									"1"
			"Wide"									"8"
			"Tall"									"8"
			"Visible"								"1"
			"Enabled"								"1"
			"Image"									"../hud/hud_mvm_bomb_upgrade_2_disabled"
			"ScaleImage"							"1"
		}
		"UpgradeLevel3"
		{
			"ControlName"							"ImagePanel"
			"FieldName"								"UpgradeLevel3"
			"XPos"									"c31"
			"YPos"									"r24"
			"ZPos"									"1"
			"Wide"									"8"
			"Tall"									"8"
			"Visible"								"1"
			"Enabled"								"1"
			"Image"									"../hud/hud_mvm_bomb_upgrade_3_disabled"
			"ScaleImage"							"1"
		}
		"UpgradeLevelBoss"
		{
			"ControlName"							"ImagePanel"
			"FieldName"								"UpgradeLevelBoss"
			"XPos"									"c10"
			"YPos"									"r24"
			"ZPos"									"1"
			"Wide"									"8"
			"Tall"									"8"
			"Visible"								"0"
			"Enabled"								"1"
			"Image"									"../hud/hud_mvm_bomb_upgrade_boss"
			"ScaleImage"							"1"
		}
	}
	"VictorySplash"
	{
		"ControlName"								"CVictorySplash"
		"FieldName"									"VictorySplash"
		"XPos"										"0"
		"YPos"										"0"
		//"ZPos"									"102"
		"Wide"										"f0"
		"Tall"										"480"
		"Visible"									"0"
		"Enabled"									"1"
	}
	"VictoryPanelContainer"
	{
		"ControlName"								"CMvMVictoryPanelContainer"
		"FieldName"									"VictoryPanelContainer"
		"XPos"										"0"
		"YPos"										"0"
		"Wide"										"f0"
		"Tall"										"480"
		"Visible"									"0"
	}
	"WaveLossPanel"
	{
		"ControlName"								"CMvMWaveLossPanel"
		"FieldName"									"WaveLossPanel"
		"XPos"										"0"
		"YPos"										"0"
		"Wide"										"f0"
		"Tall"										"480"
		"Visible"									"0"
	}
	"ServerChangeMessage"
	{
		"ControlName"								"EditablePanel"
		"FieldName"									"ServerChangeMessage"
		"XPos"										"0"
		"YPos"										"0"
		"Wide"										"f0"
		"Tall"										"480"
		"Visible"									"0"

		"ServerChangeLabel"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"ServerChangeLabel"
			"XPos"									"cs-0.5"
			"YPos"									"80"
			"Wide"									"180"
			"Tall"									"16"
			"Visible"								"1"
			"Enabled"								"1"
			"ProportionalToParent"					"1"
			"Font"									"m0refont12Shadow"
			"TextAlignment"							"center"
			"LabelText"								"%servermessage%"
			"FGColor"								"White"
		}
		"Background"
		{
			"ControlName"							"ScalableImagePanel"
			"FieldName"								"Background"
			"XPos"									"9999"
			"YPos"									"9999"
			"Wide"									"0"
			"Tall"									"0"
			"Visible"								"0"
			"Enabled"								"0"
		}
	}
}