"Resource/UI/HudPasstimePassNotify.res"
{
	"HudPasstimePassNotify"
	{
		"ControlName"								"EditablePanel"
		"FieldName"									"HudPasstimePassNotify"
		"XPos"										"0"
		"YPos"										"16"
		"ZPos"										"0"
		"Wide"										"f0"
		"Tall"										"480"
		"Visible"									"1"
		"Enabled"									"1"
	}
	"TextBox"
	{
		"ControlName"								"EditablePanel"
		"FieldName"									"TextBox"
		"XPos"										"c-100"
		"YPos"										"c-220"
		"ZPos"										"1"
		"Wide"										"200"
		"Tall"										"35"
		"Visible"									"1"
		"Enabled"									"1"
		"Border"									"TFFatLineBorder"
		"RoundedCorners"							"255"

		"TextInPassRange"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"TextInPassRange"
			"Font"									"m0refont12"
			"XPos"									"-50"
			"YPos"									"-5"
			"ZPos"									"3"
			"Wide"									"300"
			"Tall"									"32"
			"Visible"								"1"
			"Enabled"								"1"
			"CenterWrap"							"1"
			"TextAlignment"							"center"
			"LabelText"								"#Msg_PasstimeInPassRange"
			"FGColor"								"White"
		}
		"TextLockedOn"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"TextLockedOn"
			"Font"									"m0refont12"
			"XPos"									"-50"
			"YPos"									"-5"
			"ZPos"									"3"
			"Wide"									"300"
			"Tall"									"40"
			"Visible"								"1"
			"Enabled"								"1"
			"CenterWrap"							"1"
			"TextAlignment"							"center"
			"LabelText"								"#Msg_PasstimeLockedOn"
			"FGColor"								"White"
		}
		"TextPassIncoming"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"TextPassIncoming"
			"Font"									"m0refont12"
			"XPos"									"-50"
			"YPos"									"-5"
			"ZPos"									"3"
			"Wide"									"300"
			"Tall"									"32"
			"Visible"								"1"
			"Enabled"								"1"
			"CenterWrap"							"1"
			"TextAlignment"							"center"
			"LabelText"								"#Msg_PasstimePassIncoming"
			"FGColor"								"White"
		}
		"TextPlayerName"
		{
			"ControlName"							"CExLabel"
			"FieldName"								"TextPlayerName"
			"Font"									"m0refont10"
			"XPos"									"-50"
			"YPos"									"17"
			"ZPos"									"3"
			"Wide"									"300"
			"Tall"									"16"
			"Visible"								"1"
			"Enabled"								"1"
			"TextAlignment"							"center"
			"LabelText"								"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
			"FGColor"								"100 255 0 255"
		}
	}
	"PassLockIndicator"
	{
		"ControlName"								"ImagePanel"
		"FieldName"									"PassLockIndicator"
		"XPos"										"-8"
		"YPos"										"14"
		"Wide"										"64"
		"ZPos"										"3"
		"Tall"										"64"
		"Visible"									"1"
		"Enabled"									"1"
		"ScaleImage"								"1"
		"Image"										"../passtime/hud/passtime_ball_reticle_incomingpass"

		"Pin_To_Sibling"							"TextBox"
		"Pin_Corner_To_Sibling"						"0"
		"Pin_To_Sibling_Corner"						"1"
	}
	"SpeechIndicator"
	{
		"ControlName"								"ImagePanel"
		"FieldName"									"SpeechIndicator"
		"XPos"										"8"
		"YPos"										"8"
		"ZPos"										"3"
		"Wide"										"48"
		"Tall"										"48"
		"Visible"									"1"
		"Enabled"									"1"
		"ScaleImage"								"1"
		"Image"										"../passtime/hud/passtime_pass_to_me_prompt"

		"Pin_To_Sibling"							"TextBox"
		"Pin_Corner_To_Sibling"						"PIN_TOPRIGHT"
		"Pin_To_Sibling_Corner"						"PIN_TOPLEFT"
	}
}