#base "../dev/reload_scheme.res"

"Resource/UI/ItemSelectionPanel.res"
{
	"ItemSelectionPanel"
	{
		"ControlName"								"EditablePanel"
		"FieldName"									"ItemSelectionPanel"
		"XPos"										"0"
		"YPos"										"0"
		"ZPos"										"500"
		"Wide"										"f0"
		"Tall"										"480"
		"Visible"									"1"
		"Enabled"									"1"
		"SetTitleBarVisible"						"0"
		"BGColor_Override"							"Background_Main"

		"Item_YPos"									"78"
		"Item_YDelta"								"80"
		"Item_Backpack_OffCenter_X"					"-286"
		"Item_Backpack_XDelta"						"3"
		"Item_Backpack_YDelta"						"3"

		"ModelPanels_Selection_KV"
		{
			"Wide"									"93"
			"Tall"									"73"
			"Model_XPos"							"2"
			"Model_Wide"							"75"
			"Model_Tall"							"50"
			"Model_Center_X"						"1"
			"Text_YPos"								"0"
			"Text_ForceSize"						"2"
			"Text_Center"							"0"
			"Text_YOffset"							"2"
			"Inset_EQ_Y"							"55"

			"Deferred_Description"					"1"
			"Deferred_Icon"							"1"
		}
		"ModelPanels_KV"
		{
			"ControlName"							"CItemModelPanel"
			"XPos"									"c-70"
			"YPos"									"270"
			"Wide"									"55"
			"Tall"									"43"
			"Visible"								"0"
			"BGColor_Override"						"Blank"
			"NoItem_TextColor"						"Gray"
			"PaintBackgroundType"					"2"
			"PaintBorder"							"1"

			"Model_XPos"							"2"
			"Model_Ypos"							"5"
			"Model_Wide"							"50"
			"Model_Tall"							"35"
			"Text_YPos"								"60"
			"Text_Center"							"1"
			"Name_Only"								"1"

			"Inset_EQ_X"							"4"
			"Inset_EQ_Y"							"2"

			"Deferred_Description"					"1"

			"ItemModelPanel"
			{
				"Use_Item_RenderTarget"				"0"
				"Allow_Rot"							"0"
			}

			"Use_Item_Sounds"						"1"
		}
		"DuplicateLabels_KV"
		{
			"Font"									"ItemFontNameSmallest"
			"TextAlignment"							"center"
			"Wide"									"14"
			"Tall"									"12"
			"ZPos"									"1"
			"Enabled"								"1"
			"FGColor"								"White"
		}
	}
	"BackpackBG"
	{
		"ControlName"								"Panel"
		"FieldName"									"BackpackBG"
		"XPos"										"c-288"
		"YPos"										"c-165"
		"ZPos"										"-1"
		"Wide"										"576"
		"Tall"										"230"
		"Visible"									"1"
		"Enabled"									"1"
		"ProportionalToParent"						"1"
		"MouseInputEnabled"							"0"
		"PaintBackground"							"1"
		"PaintBackgroundType"						"0"
		"BGColor_Override"							"Background_Dark"
	}
	"FiltersBG"
	{
		"ControlName"								"Panel"
		"FieldName"									"FiltersBG"
		"XPos"										"0"
		"YPos"										"3"
		"ZPos"										"-1"
		"Wide"										"576"
		"Tall"										"20"
		"Visible"									"1"
		"Enabled"									"1"
		"ProportionalToParent"						"1"
		"MouseInputEnabled"							"0"
		"PaintBackground"							"1"
		"PaintBackgroundType"						"0"
		"BGColor_Override"							"Background_Dark"

		"Pin_To_Sibling"							"BackpackBG"
		"Pin_Corner_To_Sibling"						"PIN_BOTTOMLEFT"
		"Pin_To_Sibling_Corner"						"PIN_TOPLEFT"
	}
	"NameFilterIcon"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"NameFilterIcon"
		"XPos"										"-2"
		"YPos"										"0"
		"ZPos"										"1"
		"Wide"										"125"
		"Tall"										"16"
		"Visible"									"1"
		"Enabled"									"1"
		"ProportionalToParent"						"1"
		"Use_Proportional_Insets"					"1"
		"TextAlignment"								"west"
		"TextInsetX"								"2"
		"LabelText"									"S"
		"Font"										"Symbols16"
		"FGColor"									"White"
		"PaintBackground"							"1"
		"PaintBackgroundType"						"0"
		"BGColor_Override"							"Background_Main"

		"Pin_To_Sibling"							"FiltersBG"
		"Pin_Corner_To_Sibling"						"PIN_CENTER_LEFT"
		"Pin_To_Sibling_Corner"						"PIN_CENTER_LEFT"
	}
	"NameFilterTextEntry"
	{
		"ControlName"								"TextEntry"
		"FieldName"									"NameFilterTextEntry"
		"XPos"										"-2"
		"YPos"										"0"
		"Wide"										"105"
		"ZPos"										"5"
		"Tall"										"12"
		"Visible"									"1"
		"Enabled"									"1"
		"TextHidden"								"0"
		"Editable"									"1"
		"Unicode"									"1"
		"FGColor_Override"							"White"
		"BGColor_Override"							"TransparentBlack"
		"Font"										"HudFontSmallest"

		"Pin_To_Sibling"							"NameFilterIcon"
		"Pin_Corner_To_Sibling"						"PIN_CENTER_RIGHT"
		"Pin_To_Sibling_Corner"						"PIN_CENTER_RIGHT"
	}
	"NoItemsLabel"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"NoItemsLabel"
		"XPos"										"0"
		"YPos"										"0"
		"ZPos"										"10"
		"Wide"										"576"
		"Tall"										"20"
		"Visible"									"0"
		"Enabled"									"1"
		"FGColor"									"Red"
		"Font"										"HudFontSmallBold"
		"LabelText"									"#NoItemsToEquip"
		"TextAlignment"								"center"

		"Pin_To_Sibling"							"FiltersBG"
		"Pin_Corner_To_Sibling"						"PIN_CENTER_TOP"
		"Pin_To_Sibling_Corner"						"PIN_CENTER_TOP"
	}
	"CancelButton"
	{
		"ControlName"								"CExButton"
		"FieldName"									"CancelButton"
		"XPos"										"c-200"
		"YPos"										"400"
		"ZPos"										"2"
		"Wide"										"200"
		"Tall"										"25"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									"#Cancel"
		"Font"										"HudFontSmallBold"
		"TextAlignment"								"center"
		"Command"									"vguicancel"
		"Sound_Depressed"							"UI/buttonclick.wav"
	}
	"OnlyAllowUniqueQuality"
	{
		"ControlName"								"CheckButton"
		"FieldName"									"OnlyAllowUniqueQuality"
		"XPos"										"c-292"
		"YPos"										"302"
		"ZPos"										"1"
		"Wide"										"290"
		"Tall"										"25"
		"Visible"									"0"
		"Enabled"									"1"
		"AllCaps"									"1"
		"SmallCheckImage"							"1"
		"LabelText"									"#OnlyAllowUniqueQuality"
		"Font"										"HudFontSmallestBold"
		"TextAlignment"								"east"
	}
	"ShowBackpack"
	{
		"ControlName"								"CExButton"
		"FieldName"									"ShowBackpack"
		"XPos"										"-2"
		"YPos"										"0"
		"ZPos"										"20"
		"Wide"										"125"
		"Tall"										"16"
		"Visible"									"1"
		"Enabled"									"1"
		"AllCaps"									"1"
		"LabelText"									"#Selection_ShowBackpack"
		"Font"										"HudFontSmallestBold"
		"TextAlignment"								"center"
		"Command"									"show_backpack"
		"Sound_Depressed"							"UI/buttonclick.wav"

		"Pin_To_Sibling"							"FiltersBG"
		"Pin_Corner_To_Sibling"						"PIN_CENTER_RIGHT"
		"Pin_To_Sibling_Corner"						"PIN_CENTER_RIGHT"
	}
	"ShowSelection"
	{
		"ControlName"								"CExButton"
		"FieldName"									"ShowSelection"
		"XPos"										"-2"
		"YPos"										"0"
		"ZPos"										"20"
		"Wide"										"125"
		"Tall"										"16"
		"Visible"									"1"
		"Enabled"									"1"
		"AllCaps"									"1"
		"LabelText"									"#Selection_ShowSelection"
		"Font"										"HudFontSmallestBold"
		"TextAlignment"								"center"
		"Command"									"show_selection"
		"Sound_Depressed"							"UI/buttonclick.wav"

		"Pin_To_Sibling"							"FiltersBG"
		"Pin_Corner_To_Sibling"						"PIN_CENTER_RIGHT"
		"Pin_To_Sibling_Corner"						"PIN_CENTER_RIGHT"
	}
	"CurPageLabel"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"CurPageLabel"
		"XPos"										"0"
		"YPos"										"0"
		"ZPos"										"1"
		"Wide"										"50"
		"Tall"										"20"
		"Visible"									"1"
		"Enabled"									"1"
		"Font"										"HudFontSmallishBold"
		"LabelText"									"%backpackpage%"
		"TextAlignment"								"center"
		"FGColor"									"White"

		"Pin_To_Sibling"							"FiltersBG"
		"Pin_Corner_To_Sibling"						"PIN_CENTER_TOP"
		"Pin_To_Sibling_Corner"						"PIN_CENTER_TOP"
	}
	"PrevPageButton"
	{
		"ControlName"								"CExButton"
		"FieldName"									"PrevPageButton"
		"XPos"										"1"
		"YPos"										"0"
		"ZPos"										"1"
		"Wide"										"14"
		"Tall"										"227"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									"<"
		"Font"										"Symbols16"
		"TextAlignment"								"center"
		"Command"									"prevpage"
		"Sound_Depressed"							"UI/buttonclick.wav"
		"PaintBackground"							"0"

		"DefaultFGColor_Override"					"White"
		"ArmedFGColor_Override"						"Menu_Accent"
		"DepressedFGColor_Override"					"White"

		"Pin_To_Sibling"							"BackpackBG"
		"Pin_Corner_To_Sibling"						"PIN_CENTER_RIGHT"
		"Pin_To_Sibling_Corner"						"PIN_CENTER_LEFT"
	}
	"NextPageButton"
	{
		"ControlName"								"CExButton"
		"FieldName"									"NextPageButton"
		"XPos"										"1"
		"YPos"										"0"
		"ZPos"										"1"
		"Wide"										"14"
		"Tall"										"227"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									">"
		"Font"										"Symbols16"
		"TextAlignment"								"center"
		"Command"									"nextpage"
		"Sound_Depressed"							"UI/buttonclick.wav"
		"PaintBackground"							"0"

		"DefaultFGColor_Override"					"White"
		"ArmedFGColor_Override"						"Menu_Accent"
		"DepressedFGColor_Override"					"White"

		"Pin_To_Sibling"							"BackpackBG"
		"Pin_Corner_To_Sibling"						"PIN_CENTER_LEFT"
		"Pin_To_Sibling_Corner"						"PIN_CENTER_RIGHT"
	}
	"PrevShortKey"
	{
		"ControlName"								"CExButton"
		"FieldName"									"PrevShortKey"
		"XPos"										"9999"
		"LabelText"									"&A"
		"Command"									"prevpage"
		"Visible"									"1"
	}
	"NextShortKey"
	{
		"ControlName"								"CExButton"
		"FieldName"									"NextShortKey"
		"XPos"										"9999"
		"LabelText"									"&D"
		"Command"									"nextpage"
		"Visible"									"1"
	}
	"MouseOverItemPanel"
	{
		"ControlName"								"CItemModelPanel"
		"FieldName"									"MouseOverItemPanel"
		"XPos"										"c-70"
		"YPos"										"270"
		"ZPos"										"100"
		"Wide"										"300"
		"Tall"										"300"
		"Visible"									"0"
		"BGColor_Override"							"Blank"
		"NoItem_TextColor"							"Gray"
		"PaintBackgroundType"						"2"
		"PaintBorder"								"1"

		"Text_YPos"									"20"
		"Text_Center"								"1"
		"Model_Hide"								"1"
		"Resize_To_Text"							"1"
		"Padding_Height"							"15"

		"AttribLabel"
		{
			"Font"									"ItemFontAttribLarge"
			"XPos"									"0"
			"YPos"									"30"
			"ZPos"									"2"
			"Wide"									"140"
			"Tall"									"60"
			"Visible"								"1"
			"Enabled"								"1"
			"LabelText"								"%attriblist%"
			"TextAlignment"							"center"
			"FGColor"								"Gray"
			"CenterWrap"							"1"
		}
	}
}