"Resource/UI/MvMWaveLossPanel.res"
{
	"DarkMask"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"DarkMask"
		"xpos"										"0"
		"ypos"										"0"
		"zpos"										"0"
		"wide"										"f0"
		"tall"										"f0"
		"visible"									"1"
		"bgcolor_override"							"TransparentMediumBlack"
	}
	"PanelBackground"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"PanelBackground"
		"xpos"										"cs-0.5"
		"ypos"										"cs-0.5"
		"wide"										"440"
		"tall"										"90"
		"visible"									"1"
		"paintbackground"							"1"
		"paintbackgroundtype"						"0"
		"bgcolor_override"							"TransparentMediumBlack"
	}
	"WaveFailHeaderShadow"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"WaveFailHeaderShadow"
		"xpos"										"0"
		"ypos"										"0"
		"wide"										"440"
		"tall"										"20"
		"font"										"m0refont16"
		"labelText"									"%waveheader%"
		"textAlignment"								"center"
		"fgcolor"									"Black"
		"paintbackground"							"1"
		"paintbackgroundtype"						"0"
		"bgcolor_override"							"Red"

		"pin_to_sibling"							"PanelBackground"
		"pin_corner_to_sibling"						"PIN_BOTTOMLEFT"
		"pin_to_sibling_corner"						"PIN_TOPLEFT"
	}
	"WaveFailHeader"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"WaveFailHeader"
		"xpos"										"1"
		"ypos"										"1"
		"zpos"										"1"
		"wide"										"440"
		"tall"										"20"
		"font"										"m0refont16"
		"labelText"									"%waveheader%"
		"textAlignment"								"center"
		"fgcolor"									"White"

		"pin_to_sibling"							"WaveFailHeaderShadow"
	}
	"CollectionContainer"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"CollectionContainer"
		"xpos"										"-10"
		"ypos"										"10"
		"wide"										"160"
		"tall"										"70"
		"visible"									"1"

		"pin_to_sibling"							"WaveFailHeader"
		"pin_corner_to_sibling"						"PIN_TOPLEFT"
		"pin_to_sibling_corner"						"PIN_BOTTOMLEFT"

		"Header"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"Header"
			"xpos"									"0"
			"ypos"									"0"
			"wide"									"160"
			"font"									"m0refont11"
			"labelText"								"#TF_PVE_Credit_Collection"
			"textAlignment"							"center"
			"fgcolor"								"White"
		}
		"CollectedLabel"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"CollectedLabel"
			"xpos"									"5"
			"ypos"									"25"
			"wide"									"120"
			"font"									"m0refont11"
			"labelText"								"#TF_PVE_Collected"
			"textAlignment"							"west"
			"fgcolor"								"White"
		}
		"CollectedCount"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"CollectedCount"
			"xpos"									"125"
			"ypos"									"25"
			"wide"									"30"
			"font"									"m0refont11"
			"labelText"								"%creditscollected%"
			"textAlignment"							"east"
			"fgcolor"								"CreditsGreen"
		}
		"MissedLabel"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"MissedLabel"
			"xpos"									"5"
			"ypos"									"40"
			"wide"									"120"
			"font"									"m0refont11"
			"labelText"								"#TF_PVE_Missed"
			"textAlignment"							"west"
			"fgcolor"								"White"
		}
		"MissedCount"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"MissedCount"
			"xpos"									"125"
			"ypos"									"40"
			"wide"									"30"
			"font"									"m0refont11"
			"labelText"								"%creditsmissed%"
			"textAlignment"							"east"
			"fgcolor"								"Red"
		}
		"BonusLabel"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"BonusLabel"
			"xpos"									"5"
			"ypos"									"55"
			"wide"									"120"
			"font"									"m0refont11"
			"labelText"								"#TF_PVE_Bonus"
			"textAlignment"							"west"
			"fgcolor"								"White"
		}
		"BonusCount"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"BonusCount"
			"xpos"									"125"
			"ypos"									"55"
			"wide"									"30"
			"font"									"m0refont11"
			"labelText"								"%creditbonus%"
			"textAlignment"							"east"
			"fgcolor"								"CreditsGreen"
		}
	}
	"UsageContainer"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"UsageContainer"
		"xpos"										"-10"
		"ypos"										"10"
		"wide"										"220"
		"tall"										"70"
		"visible"									"1"

		"pin_to_sibling"							"WaveFailHeader"
		"pin_corner_to_sibling"						"PIN_TOPRIGHT"
		"pin_to_sibling_corner"						"PIN_BOTTOMRIGHT"

		"Header"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"Header"
			"xpos"									"0"
			"ypos"									"0"
			"wide"									"220"
			"font"									"m0refont11"
			"labelText"								"#TF_PVE_Credit_Use"
			"textAlignment"							"center"
			"fgcolor"								"White"
		}
		"YouLabel"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"YouLabel"
			"xpos"									"125"
			"ypos"									"15"
			"wide"									"35"
			"font"									"m0refont9"
			"labelText"								"#TF_PVE_You"
			"textAlignment"							"east"
			"fgcolor"								"White"
		}
		"TeamLabel"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"TeamLabel"
			"xpos"									"180"
			"ypos"									"15"
			"wide"									"35"
			"font"									"m0refont9"
			"labelText"								"#Winpanel_Team2"
			"textAlignment"							"east"
			"fgcolor"								"White"
		}
		"BuybackLabel"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"BuybackLabel"
			"xpos"									"5"
			"ypos"									"25"
			"wide"									"120"
			"font"									"m0refont11"
			"labelText"								"#TF_PVE_Buybacks"
			"textAlignment"							"west"
			"fgcolor"								"White"
		}
		"BuybackCountYou"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"BuybackCountYou"
			"xpos"									"125"
			"ypos"									"25"
			"wide"									"35"
			"font"									"m0refont11"
			"labelText"								"%buybacksyou%"
			"textAlignment"							"east"
			"fgcolor"								"White"
		}
		"BuybackCountTeam"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"BuybackCountTeam"
			"xpos"									"180"
			"ypos"									"25"
			"wide"									"35"
			"font"									"m0refont11"
			"labelText"								"%buybacksteam%"
			"textAlignment"							"east"
			"fgcolor"								"White"
		}
		"BottleLabel"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"BottleLabel"
			"xpos"									"5"
			"ypos"									"40"
			"wide"									"120"
			"font"									"m0refont11"
			"labelText"								"#TF_PVE_Bottles"
			"textAlignment"							"west"
			"fgcolor"								"White"
		}
		"BottleCountYou"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"BottleCountYou"
			"xpos"									"125"
			"ypos"									"40"
			"wide"									"35"
			"font"									"m0refont11"
			"labelText"								"%bottlesyou%"
			"textAlignment"							"east"
			"fgcolor"								"White"
		}
		"BottleCountTeam"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"BottleCountTeam"
			"xpos"									"180"
			"ypos"									"40"
			"wide"									"35"
			"font"									"m0refont11"
			"labelText"								"%bottlesteam%"
			"textAlignment"							"east"
			"fgcolor"								"White"
		}
		"InactiveLabel"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"InactiveLabel"
			"xpos"									"5"
			"ypos"									"55"
			"wide"									"120"
			"font"									"m0refont11"
			"labelText"								"#TF_PVE_Inactive_Upgrades"
			"textAlignment"							"west"
			"fgcolor"								"White"
		}
		"InactiveCountYou"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"InactiveCountYou"
			"xpos"									"125"
			"ypos"									"55"
			"wide"									"35"
			"font"									"m0refont11"
			"labelText"								"%inactiveupgradesyou%"
			"textAlignment"							"east"
			"fgcolor"								"Red"
		}
		"InactiveCountTeam"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"InactiveCountTeam"
			"xpos"									"180"
			"ypos"									"55"
			"wide"									"35"
			"font"									"m0refont11"
			"labelText"								"%inactiveupgradesteam%"
			"textAlignment"							"east"
			"fgcolor"								"Red"
		}
	}
	"VoteButton"
	{
		"ControlName"								"CExImageButton"
		"fieldName"									"VoteButton"
		"xpos"										"0"
		"ypos"										"2"
		"zpos"										"999"
		"wide"										"440"
		"tall"										"16"
		"enabled"									"1"
		"labelText"									"#TF_PVE_Vote_MissionRestart"
		"font"										"m0refont14"
		"textAlignment"								"center"
		"AllCaps"									"1"
		"Command"									"vote_restart"
		"sound_depressed"							"UI/buttonclick.wav"

		"paintbackground"							"1"
		"roundedcorners"							"0"

		"defaultFgColor_override"					"White"
		"armedFgColor_override"						"White"
		"depressedFgColor_override"					"White"

		"defaultBgColor_override"					"TransparentBlack"
		"armedBgColor_override"						"Menu_Accent"
		"depressedBgColor_override"					"Menu_Accent"

		"pin_to_sibling"							"PanelBackground"
		"pin_corner_to_sibling"						"PIN_TOPLEFT"
		"pin_to_sibling_corner"						"PIN_BOTTOMLEFT"
	}
	"ContinueButton"
	{
		"ControlName"								"CExImageButton"
		"fieldName"									"ContinueButton"
		"xpos"										"0"
		"ypos"										"2"
		"ypos"										"2"
		"zpos"										"1000"
		"wide"										"440"
		"tall"										"16"
		"enabled"									"1"
		"labelText"									"#ConfirmButtonText"
		"font"										"m0refont14"
		"textAlignment"								"center"
		"Command"									"continue"
		"sound_depressed"							"UI/buttonclick.wav"

		"paintbackground"							"1"
		"roundedcorners"							"0"

		"defaultFgColor_override"					"White"
		"armedFgColor_override"						"White"
		"depressedFgColor_override"					"White"

		"defaultBgColor_override"					"TransparentBlack"
		"armedBgColor_override"						"Menu_Accent"
		"depressedBgColor_override"					"Menu_Accent"

		"pin_to_sibling"							"VoteButton"
		"pin_corner_to_sibling"						"PIN_TOPLEFT"
		"pin_to_sibling_corner"						"PIN_BOTTOMLEFT"
	}
}