// Used to quickly test the size difference between optional fonts

"Resource/DEV/font_sizing.res"
{
	"Health"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"Health"
		"XPos"										"c-249"
		"XPos_Minmode"								"c-144"
		"YPos"										"c95"
		"YPos_Minmode"								"c45"
		"ZPos"										"2"
		"Wide"										"150"
		"Wide_Minmode"								"100"
		"Tall"										"80"
		"Tall_Minmode"								"40"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									"200"
		"TextAlignment"								"center"
		"Font"										"Default_Health"
		"Font_Minmode"								"Default_Health_Minmode"
		"FGColor"									"Red"
		"Alpha"										"200"
	}
	"Ammo_Clip"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"Ammo_Clip"
		"XPos"										"c25"
		"XPos_Minmode"								"c25"
		"YPos"										"c95"
		"YPos_Minmode"								"c45"
		"ZPos"										"2"
		"Wide"										"150"
		"Wide_Minmode"								"70"
		"Tall"										"80"
		"Tall_Minmode"								"40"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									"4"
		"TextAlignment"								"east"
		"Font"										"Default_Health"
		"Font_Minmode"								"Default_Health_Minmode"
		"FGColor"									"Red"
		"Alpha"										"200"
	}
	"Ammo_Reserve"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"Ammo_Reserve"
		"XPos"										"c180"
		"XPos_Minmode"								"c100"
		"YPos"										"c99"
		"YPos_Minmode"								"c46"
		"ZPos"										"2"
		"Wide"										"150"
		"Wide_Minmode"								"40"
		"Tall"										"80"
		"Tall_Minmode"								"40"
		"Visible"									"1"
		"Enabled"									"1"
		"LabelText"									"20"
		"TextAlignment"								"west"
		"Font"										"Default_Ammo_Reserve"
		"Font_Minmode"								"Default_Ammo_Reserve_Minmode"
		"FGColor"									"Red"
		"Alpha"										"200"
	}
	"Damage_Simulator"
	{
		"ControlName"								"CExLabel"
		"FieldName"									"Damage_Simulator"
		"XPos"										"cs-0.5"
		"YPos"										"cs-0.5+50"
		"ZPos"										"2"
		"Wide"										"100"
		"Tall"										"100"
		"Visible"									"0"
		"Enabled"									"1"
		"LabelText"									"-156"
		"TextAlignment"								"center"
		"Font"										"m0refont18Outline"
		//"Font"									"m0refont18Numbers"
		//"Font"									"m0refont24Outline"
		//"Font"									"m0refont24Numbers"
		//"Font"									"m0refont30Outline"
		//"Font"									"m0refont30Numbers"
		"FGColor"									"White"
	}
}