// Used to quickly test the size difference between optional fonts

"Resource/DEV/font_sizing.res"
{
	"Health"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"Health"
		"xpos"										"c-249"
		"xpos_minmode"								"c-144"
		"ypos"										"c95"
		"ypos_minmode"								"c45"
		"zpos"										"2"
		"wide"										"150"
		"wide_minmode"								"100"
		"tall"										"80"
		"tall_minmode"								"40"
		"visible"									"1"
		"enabled"									"1"
		"labeltext"									"200"
		"textalignment"								"center"
		"font"										"Default_Health"
		"font_minmode"								"Deafult_Health_Minmode"
		"fgcolor"									"Red"
	}
	"Ammo_Clip"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"Ammo_Clip"
		"xpos"										"c25"
		"xpos_minmode"								"c25"
		"ypos"										"c95"
		"ypos_minmode"								"c45"
		"zpos"										"2"
		"wide"										"150"
		"wide_minmode"								"70"
		"tall"										"80"
		"tall_minmode"								"40"
		"visible"									"1"
		"enabled"									"1"
		"labeltext"									"4"
		"textalignment"								"east"
		"font"										"Default_Health"
		"font_minmode"								"Deafult_Health_Minmode"
		"fgcolor"									"Red"
	}
	"Ammo_Reserve"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"Ammo_Reserve"
		"xpos"										"c180"
		"xpos_minmode"								"c100"
		"ypos"										"c99"
		"ypos_minmode"								"c46"
		"zpos"										"2"
		"wide"										"150"
		"wide_minmode"								"40"
		"tall"										"80"
		"tall_minmode"								"40"
		"visible"									"1"
		"enabled"									"1"
		"labeltext"									"20"
		"textalignment"								"west"
		"font"										"Default_Ammo_Reserve"
		"font_minmode"								"Default_Ammo_Reserve_Minmode"
		"fgcolor"									"Red"
	}
	"Damage_Simulator"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"Damage_Simulator"
		"xpos"										"cs-0.5"
		"ypos"										"cs-0.5+50"
		"zpos"										"2"
		"wide"										"100"
		"tall"										"100"
		"visible"									"0"
		"enabled"									"1"
		"labeltext"									"-156"
		"textalignment"								"center"
		"font"										"m0refont18Outline"
		//"font"									"m0refont18Numbers"
		//"font"									"m0refont24Outline"
		//"font"									"m0refont24Numbers"
		//"font"									"m0refont30Outline"
		//"font"									"m0refont30Numbers"
		"fgcolor"									"White"
	}
}